version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m -Xmax-classfile-name 256

      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
        
      - run: cat /dev/null | sbt test:test

  release:
    docker:
        - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m -Xmax-classfile-name 256
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt release

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master